version: "3"

services:
  trullo_app:
    container_name: trullo_clone
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ./src:/src
    depends_on:
      - trullo_db

  trullo_db:
    image: postgres:13
    container_name: trullo_db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
